#!/bin/bash

if test x"$GJS_PATH" = x ; then
    export GJS_PATH=/home/c-a/Programmering/gnome/build/share/gnome-todo/js
else
    export GJS_PATH=/home/c-a/Programmering/gnome/build/share/gnome-todo/js:$GJS_PATH
fi

if test x"$GI_TYPELIB_PATH" = x ; then
    export GI_TYPELIB_PATH=/home/c-a/Programmering/gnome/build/lib64/gnome-todo/girepository-1.0
else
    export GI_TYPELIB_PATH=/home/c-a/Programmering/gnome/build/lib64/gnome-todo/girepository-1.0:$GI_TYPELIB_PATH
fi

if test x"$LD_LIBRARY_PATH" = x ; then
    export LD_LIBRARY_PATH=/home/c-a/Programmering/gnome/build/lib64/gnome-todo
else
    export LD_LIBRARY_PATH=/home/c-a/Programmering/gnome/build/lib64/gnome-todo:$LD_LIBRARY_PATH
fi

if test x"$GJS_DEBUG_OUTPUT" = x ; then
    export GJS_DEBUG_OUTPUT=stderr
fi

if test x"$GJS_DEBUG_TOPICS" = x ; then
    export GJS_DEBUG_TOPICS="JS ERROR;JS LOG"
fi

gdb --args /home/c-a/Programmering/gnome/build/bin/gjs-console -I /home/c-a/Programmering/gnome/build/share/gnome-todo/js -c "const Main = imports.main; Main.start();" "$@"
